# Generated by Django 3.2.7 on 2021-10-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Mężczyzna', 'Mężczyzna'), ('Kobieta', 'Kobieta')], default='Mężczyzna', max_length=30, verbose_name='status'),
        ),
    ]
