# Generated by Django 3.2.7 on 2021-10-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Zwykły', 'Zwykły'), ('Administrator', 'Administrator')], default='Mężczyzna', max_length=30, verbose_name='status'),
        ),
    ]
