# Generated by Django 3.2.7 on 2021-10-11 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Katolickie Warsztaty Taneczne', max_length=30, verbose_name='Nazwa wydarzenia')),
                ('edition', models.SmallIntegerField(verbose_name='Edycja')),
                ('city', models.CharField(max_length=30, verbose_name='Miasto')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data wydarzenia')),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, upload_to='posters/%Y/%m/%d', verbose_name='Plakat')),
                ('users_limit', models.SmallIntegerField(default=16, verbose_name='Limit uczestników')),
                ('registration', models.CharField(choices=[('Otwarta', 'Otwarta'), ('Zamknięta', 'Zamknięta')], default='Otwarta', max_length=20, verbose_name='Rejestracja')),
                ('archives', models.CharField(choices=[('Nie', 'Nie'), ('Tak', 'Tak')], default='Nie', max_length=20, verbose_name='Przenieś do archiwum')),
                ('declarations', models.ManyToManyField(blank=True, related_name='declared', to=settings.AUTH_USER_MODEL, verbose_name='Deklaracje udziału')),
                ('users', models.ManyToManyField(blank=True, related_name='verified', to=settings.AUTH_USER_MODEL, verbose_name='Uczestnicy zweryfikowani')),
            ],
        ),
        migrations.CreateModel(
            name='EventNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tytuł')),
                ('text', models.TextField(verbose_name='Treść')),
                ('image', models.ImageField(blank=True, null=True, upload_to='eventnews/%Y/%m/%d', verbose_name='obraz/plakat/zdjecie')),
                ('created', models.DateField(verbose_name='Data utworzenia')),
                ('publicated', models.DateField(verbose_name='Data opublikowania')),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Auto', max_length=30, verbose_name='Nazwa')),
                ('free_chair', models.SmallIntegerField(verbose_name='liczba wolnych miejsc')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
                ('reserved', models.ManyToManyField(blank=True, related_name='rezerwacja', to=settings.AUTH_USER_MODEL, verbose_name='Rezerwacja')),
                ('to_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Wydarzenie')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Tylko na imprezie integracyjnej od 21:00 do 24:00 (cena 39 zł)', 'Tylko na imprezie integracyjnej od 21:00 do 24:00 (cena 39 zł)'), ('W całodniowych warsztatach od 09:00 do 24:00 (cena 149 zł)', 'W całodniowych warsztatach od 09:00 do 24:00 (cena 149 zł)')], default='Tylko na imprezie integracyjnej od 21:00 do 24:00 (cena 39 zł)', max_length=100, verbose_name='Chcę uczestniczyć')),
                ('question1', models.TextField(max_length=300, verbose_name='Skąd dowiedziała się Pani/Pan o Warsztatach (znajomi, jeśli FB to jaka nazwa grupy)')),
                ('question2', models.TextField(max_length=300, verbose_name='Miasto, z którego będzie Pan/Pani wyruszać na warsztaty')),
                ('question3', models.TextField(max_length=300, verbose_name='Jeśli jedzie Pani/Pan autem, to przez jakie miasta i czy Pani/Pan miałaby/łby wolne miejsca?')),
                ('question4', models.TextField(max_length=300, verbose_name='Czy ma Pani/Pan jakieś doświadczenie taneczne? Jeśli tak, proszę napisać, czy uczestniczył/a Pani/Pan w kursach tańcach, np. poziom P0, P1, P2, jeśli tak to jakich? Czy posiada Pani/Pan klasy taneczne? Czy zaczyna Pani/Pan absolutnie od podstaw? Proszę podać, do jakich szkół tańca Pani/Pan uczęszczał/a oraz staż tańca.')),
                ('question5', models.TextField(max_length=300, verbose_name='Czy wierzy Pani/Pan w Boga i jest Pani/Pan praktykującym katolikiem?')),
                ('question6', models.TextField(max_length=300, verbose_name='Czy należy Pan/Pani do jakiejś wspólnoty? (Jeśli tak, proszę podać nazwę i miasto, w którym odbywają się spotkania.)')),
                ('question7', models.TextField(max_length=300, verbose_name='Czy uczestniczył/a Pani/Pan w rekolekcjach? Jeśli tak to jakich?')),
                ('question8', models.TextField(max_length=300, verbose_name='Czy gra Pani / Pan śpiewa lub gra na jakimś instrumencie (gitara, skrzypce etc)? ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
