# Generated by Django 3.2.7 on 2021-10-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='comment',
            field=models.TextField(max_length=300, verbose_name='Wiadomość'),
        ),
    ]
