# Generated by Django 3.2.7 on 2021-10-19 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0006_auto_20211019_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagetoadmin',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminmessage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessagetoadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermessage', to=settings.AUTH_USER_MODEL),
        ),
    ]
