# Generated by Django 3.2.7 on 2021-10-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20211019_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagetoadmin',
            name='noreaded',
            field=models.SmallIntegerField(default=0, verbose_name='Nieprzeczytane'),
        ),
    ]
