# Generated by Django 3.2.7 on 2021-10-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_chatmessagetoadmin_noreaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagetoadmin',
            name='noreaded',
            field=models.BooleanField(default=True, verbose_name='Nieprzeczytane'),
        ),
    ]
