# Generated by Django 3.2.7 on 2021-10-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_chatmessagetoadmin_noreaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
