# Generated by Django 3.2.7 on 2021-10-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_candidate_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
