# Generated by Django 3.2.7 on 2021-10-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20211021_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventnews',
            name='image',
        ),
    ]
