# Generated by Django 3.2.7 on 2021-10-22 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_remove_eventnews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bank_nr',
            field=models.BigIntegerField(default=1234567898765432, validators=[django.core.validators.MaxValueValidator(9999999999999999), django.core.validators.MinValueValidator(1)], verbose_name='Numer konta do przelewów'),
            preserve_default=False,
        ),
    ]
