# Generated by Django 3.2.7 on 2021-10-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20211022_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bank_nr',
            field=models.CharField(max_length=24, verbose_name='Numer konta'),
        ),
    ]
