# Generated by Django 3.2.7 on 2021-10-28 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0017_carchat_carchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carchatmessage',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carmessage', to='event.car'),
        ),
        migrations.AlterField(
            model_name='carchatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caruser', to=settings.AUTH_USER_MODEL),
        ),
    ]
