# Generated by Django 3.2.7 on 2021-10-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_auto_20211028_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carchatmessage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmessage', to='event.car'),
        ),
    ]
