# Generated by Django 3.2.7 on 2021-10-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_alter_carchatmessage_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carchat',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_chat', to='event.car', unique=True),
        ),
        migrations.AlterField(
            model_name='carchatmessage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmessage', to='event.car', unique=True),
        ),
    ]
